#!/bin/sh

if [ -z "$1" ]
  then
    targetFps=10000
  else
    targetFps=$1
fi
robloxPath=$(find /Applications -name Roblox.app -print -quit 2>/dev/null)

if [ -z "$robloxPath" ]; then
  $robloxPath=$(find ~/Applications -name Roblox.app -print -quit 2>/dev/null)
  if [ -z "$robloxPath" ]; then
    $robloxPath=$(find ~ -name Roblox.app -print -quit 2>/dev/null)
    if [ -z "$robloxPath" ]; then
      echo "Roblox installation folder couldn't be found."
      exit
    fi
  fi
fi

clientSettingsPath="$robloxPath/Contents/MacOS/ClientSettings"

if [ ! -d "$clientSettingsPath" ]; then
  mkdir $clientSettingsPath
fi

echo "{\"DFIntTaskSchedulerTargetFps\": $targetFps}" > "$clientSettingsPath/ClientAppSettings.json"
echo "The FPS unlocker has been installed in $robloxPath"
